module "debian-base" {
  source = "./../modules/debian-base"

    proxmox_api_url         = var.proxmox_api_url
    proxmox_username        = var.proxmox_username
    proxmox_token_id        = var.proxmox_token_id
    proxmox_token           = var.proxmox_token
    storage_pool            = var.storage_pool
    vmid                    = var.vmid
    password                = var.password
    user                    = var.user
    node                    = var.node
    template_name           = var.template_name
    template_path           = var.template_path
    public_key_path         = var.public_key_path
    private_key_path        = var.private_key_path
    memory                  = var.memory
    disk_size               = var.disk_size
    arch                    = var.arch
    cores                   = var.cores
    cpulimit                = var.cpulimit
    swap                    = var.swap
    onboot                  = var.onboot
    start                   = var.start
    ip                      = var.ip
    gw                      = var.gw
    tags                    = var.tags
    host                    = var.ip
    name                    = var.name
}