services:
  migrator:
    build: .
    restart: "no"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    command: flask db upgrade

  inventory:
    build: .
    depends_on:
      - migrator
    ports:
      - "80:8000"
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}